import {
  BatteryCharging,
  GitPullRequest,
  Layers,
  RadioTower,
  SquareKanban,
  WandSparkles,
} from "lucide-react";

interface Reason {
  title: string;
  description: string;
  icon: React.ReactNode;
}

interface FeatureSection3Props {
  heading?: string;
  reasons?: Reason[];
}

const FeatureSection3 = ({
  heading = "Reach humans, not spam folders",
  reasons = [
    {
      title: "Proactive blocklist tracking",
      description:
        "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by MailTea.",
      icon: <GitPullRequest className="size-5" />,
    },
    {
      title: "Faster Time to Inbox",
      description:
        "Send emails from the region closest to your users. Reduce delivery latency with North American, South American, European, and Asian regions.",
      icon: <SquareKanban className="size-5" />,
    },
    {
      title: "Build confidence with BIMI",
      description:
        "Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC - the email equivalent of a checkmark on social media.",
      icon: <RadioTower className="size-5" />,
    },
    {
      title: "Managed Dedicated IPs",
      description:
        "Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.",
      icon: <WandSparkles className="size-5" />,
    },
    {
      title: "Dynamic suppression list",
      description:
        "Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.",
      icon: <Layers className="size-5" />,
    },
    {
      title: "IP and domain monitoring",
      description:
        "Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.",
      icon: <BatteryCharging className="size-5" />,
    },
    {
      title: "Verify DNS records",
      description:
        "Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF.",
      icon: <BatteryCharging className="size-5" />,
    },
    {
      title: "Battle-tested infrastructure",
      description:
        "Rely on a platform of reputable IP's used by trustworthy senders with distributed workloads across different IP pools.",
      icon: <BatteryCharging className="size-5" />,
    },
    {
      title: "Prevent spoofing with DMARC",
      description:
        "Avoid impersonation by creating DMARC policies and instructing inbox providers on how to treat unauthenticated email.",
      icon: <BatteryCharging className="size-5" />,
    },
  ],
}: FeatureSection3Props) => {
  return (
    <section className="py-16  ">
      <div className="container border-t-2 rounded-4xl shadow-black/10 px-8 py-18">
        <div className="mb-6 md:mb-14">
          <p className="mb-2 text-left text-3xl font-normal  lg:text-5xl">
            Reach humans, not <br/> spam folders
          </p>
        </div>
        <div className="grid gap-10 md:grid-cols-2 lg:grid-cols-3">
          {reasons.map((reason, i) => (
            <div key={i} className="flex flex-col">
              <div className="mb-0 flex size-10 items-center text-white/60 rounded-full bg-accent">
                {reason.icon}
              </div>
              <p className="mb-1 text-md font-normal">{reason.title}</p>
              <p className="text-muted-foreground  text-justify pr-18 text-xs">{reason.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export { FeatureSection3 };
